name: Pike Module (pmod)

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths: ["chocolatey/**"]

jobs:

  build-choco:
    runs-on: windows-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Download Pike
        shell: pwsh
        run: |
          Invoke-WebRequest -URI http://pike.lysator.liu.se/pub/pike/latest-stable/Pike-v8.0.1738-Windows7-x86.msi -OutFile pike.msi
      - name: Build choco
        shell: pwsh
        run: |
          choco new -h
