name: Build Pike Chocolatey package

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths: ["chocolatey/**"]

jobs:

  build-choco:
    runs-on: windows-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      # - name: Download Pike
      #   shell: pwsh
      #   run: |
      #     Invoke-WebRequest -URI http://pike.lysator.liu.se/pub/pike/latest-stable/Pike-v8.0.1738-Windows7-x86.msi -OutFile pike.msi
      - name: Show choco help
        shell: pwsh
        run: |
          choco new -h
      - name: Build choco
        shell: pwsh
        run: |
          choco new pike url="'http://pike.lysator.liu.se/pub/pike/latest-stable/Pike-v8.0.1738-Windows7-x86.msi'"
      - name: Show template
        shell: pwsh
        run: |
          type D:\a\pike-chocolatey\pike-chocolatey\pike\*
          type D:\a\pike-chocolatey\pike-chocolatey\pike\tools\*